// <auto-generated />
namespace Altkom.RentBikes.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddModifiedDateToStation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddModifiedDateToStation));
        
        string IMigrationMetadata.Id
        {
            get { return "201608180813278_AddModifiedDateToStation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
